name: craftlink_ai
description: AI marketplace for marginalized artisans
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  speech_to_text: ^7.3.0
  google_mlkit_image_labeling: ^0.16.1
  google_mlkit_language_id: ^0.15.1
  record: ^7.1.1
  http: ^1.6.0
  path_provider: ^2.1.6
  flutter_tts: ^4.2.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
